### PR TITLE
Kd db connect

### PR DESCRIPTION
**Pull request by KDD87**
I added basic conditional rendering to APP.jsx and worked on getting my  renteeProfile component functional

### CODE REVIEW

**Review by juchengca — COMMENTED** [review]
hey kyle, maybe comment out the conditional render of rentee page for the merge?

**Comment by KDD87** [comment]
Thanks Justin for the comment, I changed some stuff around and commented out all but the HomeBar. I set up a basic home bar for now to test but when Kevin gets back hopefully we can replace it with his.

**Review by juchengca — CHANGES_REQUESTED** [review]
looks good but i think you commited bundle.js.LICENSE.txt

add that to gitignore?

**Comment by KDD87** [comment]
Ahh thanks for catching it!  could you just delete that file before merging it? Im not sure how to fix it. I already added it to my gitignore before my last commit. but for some reason its not shaded it out in the left column of file structure in vscode like it is for bundle.js and .env.

**Comment by cwillsea** [comment]
It isnt really a blocker concerning the LICENSE.txt. In my opinion. That doesnt hurt much in the efforts toward MVP.

**Pull request merged**
